fix: regex for capturing vercel preview links
aaimio/vercel-preview-url-action pull request #131
Opened 2022-04-22 03:40 UTC by yashimwong

howdy?

2022-04-24 05:50 UTC, aaimio requested changes

2022-04-24 05:50 UTC, aaimio commented on action.yml
> +    default: '\[Visit Preview\]\((.*.sx)\)' # Do use single quotes, do NOT use delimiters.
Hello old friend! :wave: 

Could we make it backward compatible so we don't unintentionally break things? If you could patch up the regex I'll add some tests to it as well.

Thanks again! Hope you're doing well.

2022-04-24 06:29 UTC, yashimwong commented on action.yml
> +    default: '\[Visit Preview\]\((.*.sx)\)' # Do use single quotes, do NOT use delimiters.
Heyy @aaimio, I'm doing well (sort of) 😆 

 I accidentally added the regex check from work. Made it more generic. For the backwards compatibility I'll have to check if there's a way to check the Vercel bot version or something 🤔

2022-04-25 04:01 UTC, aaimio commented on action.yml
> +    default: '\[Visit Preview\]\((.*.sx)\)' # Do use single quotes, do NOT use delimiters.
No need, you could add a simple OR operator in the regex.

2022-10-25 12:28 UTC, batista commented
hey guys, thanks for the project, whats the status of this? any chance this gets in? :)

2022-10-26 03:08 UTC, aaimio commented
> hey guys, thanks for the project, whats the status of this? any chance this gets in? :)
> 
> BTW, you might want to make this matching lazy with `\[Visit Preview\]\((.*?)\)`, otherwise other data is being captured

Let me have a look later today and get this done @batista

2022-11-06 11:43 UTC, aaimio commented
Fixed in https://github.com/aaimio/vercel-preview-url-action/pull/160

2022-11-06 11:43 UTC, closed without merging